---
title: "変数の種類"
editor: visual
---

## 変数の種類

　変数にはさまざまな種類がある。特に以下の4つに分類することが多い。

| 変数の種類 | 特徴                                                                            |
|:-----------|:--------------------------------------------------------------------------------|
| **名義尺度**   | 取りうる値の間に順序関係が成り立たないもの。                                    |
| **順序尺度**   | 取りうる値の間に大小関係は成り立つが、1単位あたりの差が等価ではないもの。       |
| **間隔尺度**   | 取りうる値の間の、1単位あたりの差が等価であるもの。                             |
| **比例尺度**   | 取りうる値の間の、1単位あたりの差が等価であり、原点0にも実質的な意味があるもの。|

### 名義尺度

**名義尺度**は、カテゴリに意味がある変数である。

- 「血液型」という変数は、「A」「B」「O」「AB」の間に順序関係がない。
- 「性別」という変数は、「男性」「女性」「その他」の間に順序関係がない。

:::{.callout-note}
#### グループ・ワーク

**先ほどダウンロードした「u001」のフォルダの中には、調査票が入っています（u001c.pdf）。その調査票の中から、名義尺度を探してみましょう。**

:::

### 順序尺度

**順序尺度**は、変数の値の間に大小関係はあるものの、その差は等しくなく、足し算や引き算には適さない変数である。平均値も意味をなさない。

- 「運動会の100m走の順位」という変数は、1位の方が5位よりも優れていることを意味するが、1位と5位を足したり引いたり、平均値を算出しても意味がない。

:::{.callout-note}
#### グループ・ワーク

**先ほどダウンロードした「u001」のフォルダの中には、調査票が入っています（u001c.pdf）。その調査票の中から、順序尺度を探してみましょう。**

:::

### 間隔尺度

**間隔尺度**は，変数の取りうる値の1単位あたりの差が等価で、足し算や引き算は可能であるが、原点0に便宜的な意味しかないため、積や商には意味がない変数のことである。

- 「西暦」という変数は、1990年と2000年の間に、10年の差があるということは意味するが、2000年は1000年の2倍というものは意味をなさない。

:::{.callout-note}
#### グループ・ワーク

**先ほどダウンロードした「u001」のフォルダの中には、調査票が入っています（u001c.pdf）。その調査票の中から、間隔尺度を探してみましょう。**

:::

### 比例尺度

**比例尺度**は、変数の取りうる値の間の1単位あたりの差が等価であるだけでなく、原点0にも実質的な意味があり、値同士の和・差・積・商の全てに意味がある変数のことである。

- 「50m走のタイム」という変数は、AさんがBさんよりt秒早いということも意味するし、CさんがDさんの2倍早いということにも意味がある。

:::{.callout-note}
#### グループ・ワーク

**先ほどダウンロードした「u001」のフォルダの中には、調査票が入っています（u001c.pdf）。その調査票の中から、比例尺度を探してみましょう。**

:::

## 社会科学における分類

　以上で、4つの尺度を見てきたが、実際の社会科学研究においては、ここまで厳密に分類することは稀である。実際には、「**質的変数**」と「**量的変数**」という2分類で十分なことがほとんどであり、一般的には名義尺度や順序尺度で測定された変数を質的変数、間隔尺度や比例尺度で測定された変数を量的変数と呼ぶ。

　質的変数と量的変数の境目も明確ではない。「賛成」「やや賛成」「やや反対」「反対」という4つの選択肢（値）をとる変数の場合、「賛成-やや賛成」と「やや賛成-やや反対」の間の間隔が等間隔であると仮定することには無理がある場合が多い。そのため、この変数を質的変数と捉えるか、量的変数と捉えるかは、最終的には変数の各値の意味を考えて、検討する必要がある。
